# Generated by Django 4.2.4 on 2023-08-31 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='Category name', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='Product name', max_length=255)),
                ('description', models.CharField(default='Product description', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('available_stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Products_Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdkeyshop.category')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdkeyshop.product')),
            ],
        ),
    ]
