# Generated by Django 4.2.4 on 2023-08-31 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdkeyshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products_Categories',
            new_name='ProductsCategories',
        ),
    ]
