# Generated by Django 4.2.4 on 2023-08-31 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdkeyshop', '0003_order_product_image_orderproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdkeyshop.product')),
            ],
        ),
    ]
